version: '3'
services:
  web:
    image: node:12.18.3
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: sh -c 'npm i --no-progress --ignore-optional && npm run dev'
